- name: ensure ethercalc user is present
  user:
    name: "{{ ethercalc_user }}"
    home: "{{ ethercalc_home }}"
    shell: "/bin/bash"
    state: present

- name: ensure https-apt-transports package is present
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https

- name: ensure nodejs key is present
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: ensure nodejs sources are present
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: 'nodesource'
  with_items:
    - "deb https://deb.nodesource.com/node_6.x jessie main"
    - "deb-src https://deb.nodesource.com/node_6.x jessie main"

- name: ensure required packages are installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ ethercalc_required_packages }}"

- name: ensure ethercalc is latest
  git:
    repo: "{{ ethercalc_repository }}"
    dest: "{{ ethercalc_path }}"
    version: "{{ ethercalc_repository_version}}"
    key_file: "{{ ethercalc_repository_key_file}}"
  become_user: "{{ ethercalc_user }}"
  register: repository

- name: install ethercalc
  command: npm install -g
  args:
    chdir: "{{ ethercalc_path }}"
  when: repository.changed

- name: ensure ethercalc systemd script is latest
  template:
    src: ethercalc.service.j2
    dest: /etc/systemd/system/ethercalc.service
    owner: root
    group: root
    mode: 0755
  notify: reload systemd
  when: (ansible_distribution == 'Debian')

- name: ensure ethercalc sysvinit script is latest
  template:
    src: ethercalc.sysvinit.j2
    dest: /etc/init.d/ethercalc
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution == 'Ubuntu'

- name: ensure ethercalc will start after system is booted
  service:
    name: ethercalc
    enabled: yes

- include: monit.yml
  when: ethercalc_monit_enabled
