- name: restart ethercalc
  service:
    name: ethercalc
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted

- name: reload monit
  service:
    name: monit
    state: reloaded

- name: reload systemd
  become: yes
  command: systemctl daemon-reload